package relayer

import (
	"context"
	"database/sql"
	"fmt"
	"strconv"
	"time"

	"github.com/nbd-wtf/go-nostr"
)

// DisappearingMessage represents a disappearing message record
type DisappearingMessage struct {
	ID         int64     `db:"id"`
	EventID    string    `db:"event_id"`
	TTLSeconds int64     `db:"ttl_seconds"`
	Expiration time.Time `db:"expiration"`
	CreatedAt  time.Time `db:"created_at"`
}

// DisappearingMessageStore interface for storing disappearing messages
type DisappearingMessageStore interface {
	StoreDisappearingMessage(ctx context.Context, msg *DisappearingMessage) error
	GetDisappearingMessage(ctx context.Context, eventID string) (*DisappearingMessage, error)
	DeleteExpiredMessages(ctx context.Context) error
	CreateSchema(ctx context.Context) error
}

// PostgresDisappearingStore implements DisappearingMessageStore for PostgreSQL
type PostgresDisappearingStore struct {
	db *sql.DB
}

func NewPostgresDisappearingStore(db *sql.DB) *PostgresDisappearingStore {
	return &PostgresDisappearingStore{db: db}
}

func (p *PostgresDisappearingStore) CreateSchema(ctx context.Context) error {
	query := `
	CREATE SCHEMA IF NOT EXISTS moss_api;
	
	CREATE TABLE IF NOT EXISTS moss_api.dismsg_messages (
		id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
		event_id varchar NOT NULL,
		ttl_seconds int8 NOT NULL,
		expiration timestamptz NOT NULL,
		created_at timestamptz NOT NULL,
		CONSTRAINT dismsg_messages_pkey PRIMARY KEY (id)
	);
	
	-- 创建索引（与现有表结构一致）
	CREATE INDEX IF NOT EXISTS disappearingmessage_created_at ON moss_api.dismsg_messages USING btree (created_at);
	CREATE INDEX IF NOT EXISTS disappearingmessage_event_id ON moss_api.dismsg_messages USING btree (event_id);
	CREATE INDEX IF NOT EXISTS disappearingmessage_expiration ON moss_api.dismsg_messages USING btree (expiration);
	CREATE UNIQUE INDEX IF NOT EXISTS dismsg_messages_event_id_key ON moss_api.dismsg_messages USING btree (event_id);
	`
	
	_, err := p.db.ExecContext(ctx, query)
	return err
}

func (p *PostgresDisappearingStore) StoreDisappearingMessage(ctx context.Context, msg *DisappearingMessage) error {
	query := `
	INSERT INTO moss_api.dismsg_messages (event_id, ttl_seconds, expiration, created_at)
	VALUES ($1, $2, $3, $4)
	ON CONFLICT (event_id) DO UPDATE SET
		ttl_seconds = EXCLUDED.ttl_seconds,
		expiration = EXCLUDED.expiration,
		created_at = EXCLUDED.created_at
	`
	
	_, err := p.db.ExecContext(ctx, query,
		msg.EventID,
		msg.TTLSeconds,
		msg.Expiration,
		msg.CreatedAt,
	)
	
	return err
}

func (p *PostgresDisappearingStore) GetDisappearingMessage(ctx context.Context, eventID string) (*DisappearingMessage, error) {
	query := `
	SELECT id, event_id, ttl_seconds, expiration, created_at
	FROM moss_api.dismsg_messages
	WHERE event_id = $1
	`
	
	var msg DisappearingMessage
	err := p.db.QueryRowContext(ctx, query, eventID).Scan(
		&msg.ID,
		&msg.EventID,
		&msg.TTLSeconds,
		&msg.Expiration,
		&msg.CreatedAt,
	)
	
	if err != nil {
		return nil, err
	}
	
	return &msg, nil
}

func (p *PostgresDisappearingStore) DeleteExpiredMessages(ctx context.Context) error {
	query := `DELETE FROM moss_api.dismsg_messages WHERE expiration < NOW()`
	_, err := p.db.ExecContext(ctx, query)
	return err
}

// DisappearingMessageSupport interface for relays that support disappearing messages
type DisappearingMessageSupport interface {
	GetDisappearingStore() DisappearingMessageStore
}

// Helper functions
func isDisappearingMessage(evt nostr.Event) bool {
	for _, tag := range evt.Tags {
		if len(tag) >= 2 && tag[0] == "l" && tag[1] == "disappearing" {
			return true
		}
	}
	return false
}

func (s *Server) handleDisappearingMessage(ctx context.Context, evt nostr.Event) error {
	s.Log.Infof("Processing disappearing message event ID: %s from %s", evt.ID, evt.PubKey)
	
	var ttl int64
	var expiration time.Time
	
	// 提取TTL和expiration信息
	for _, tag := range evt.Tags {
		if len(tag) < 2 {
			continue
		}
		
		switch tag[0] {
		case "ttl":
			var err error
			ttl, err = strconv.ParseInt(tag[1], 10, 64)
			if err != nil {
				return fmt.Errorf("invalid ttl value: %v", err)
			}
			if ttl <= 0 {
				return fmt.Errorf("TTL must be positive, got %d", ttl)
			}
		case "expiration":
			timestamp, err := strconv.ParseInt(tag[1], 10, 64)
			if err != nil {
				return fmt.Errorf("invalid expiration timestamp: %v", err)
			}
			expiration = time.Unix(timestamp, 0)
			if expiration.Before(time.Now()) {
				return fmt.Errorf("message already expired")
			}
		}
	}

	// 验证必要的标签
	if ttl == 0 {
		return fmt.Errorf("missing ttl tag")
	}
	if expiration.IsZero() {
		return fmt.Errorf("missing expiration tag")
	}

	// 验证expiration时间必须大于created_at+ttl
	createdAt := time.Unix(int64(evt.CreatedAt), 0)
	minExpiration := createdAt.Add(time.Duration(ttl) * time.Second)
	if expiration.Before(minExpiration) {
		return fmt.Errorf("expiration time must be greater than created_at + ttl")
	}

	// 获取阅后即焚消息存储器
	disappearingStore, ok := s.relay.(DisappearingMessageSupport)
	if !ok {
		return fmt.Errorf("disappearing message store not configured")
	}

	store := disappearingStore.GetDisappearingStore()
	if store == nil {
		return fmt.Errorf("disappearing message store not available for this backend")
	}

	// 存储到数据库
	msg := &DisappearingMessage{
		EventID:    evt.ID,
		TTLSeconds: ttl,
		Expiration: expiration,
		CreatedAt:  createdAt,
	}

	if err := store.StoreDisappearingMessage(ctx, msg); err != nil {
		return fmt.Errorf("failed to store disappearing message: %v", err)
	}
	
	s.Log.Infof("Successfully saved disappearing message %s (TTL: %d, Expires: %s)",
		evt.ID, ttl, expiration.Format(time.RFC3339))
	
	return nil
}

// handle disappearing message list in a transaction
func (s *Server) handleDisappearingMessageList(ctx context.Context, evt []nostr.Event) error {
	if len(evt) == 0 {
		return nil
	}
	s.Log.Infof("Processing disappearing message list with %d events", len(evt))
	disappearingStore, ok := s.relay.(DisappearingMessageSupport)
	if !ok {
		return fmt.Errorf("disappearing message store not configured")
	}
	store := disappearingStore.GetDisappearingStore()
	if store == nil {
		return fmt.Errorf("disappearing message store not available for this backend")
	}
	tx, err := store.(*PostgresDisappearingStore).db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer func() {
		if err != nil {
			if rollbackErr := tx.Rollback(); rollbackErr != nil {
				s.Log.Errorf("Failed to rollback transaction: %v", rollbackErr)
			}
		} else {
			if commitErr := tx.Commit(); commitErr != nil {
				s.Log.Errorf("Failed to commit transaction: %v", commitErr)
			}
		}
	}()
	for _, e := range evt {
		ttl, expiration := int64(0), time.Time{}
		for _, tag := range e.Tags {
			if len(tag) < 2 {
				continue
			}
			switch tag[0] {
			case "ttl":
				var err error
				ttl, err = strconv.ParseInt(tag[1], 10, 64)
				if err != nil {
					continue // skip if invalid ttl
				}
				if ttl <= 0 {
					continue // skip if TTL is not positive
				}
			case "expiration":
				timestamp, err := strconv.ParseInt(tag[1], 10, 64)
				if err != nil {
					continue // skip if invalid timestamp
				}
				expiration = time.Unix(timestamp, 0)
				if expiration.Before(time.Now()) {
					continue // skip if message already expired
				}
			}
		}
		if ttl == 0 {
			continue // skip if no ttl tag found
		}
		if expiration.IsZero() {
			continue // skip if no expiration tag found
		}
		createdAt := time.Unix(int64(e.CreatedAt), 0)
		minExpiration := createdAt.Add(time.Duration(ttl) * time.Second)
		if expiration.Before(minExpiration) {
			continue // skip if expiration is not greater than created_at + ttl
		}
		msg := &DisappearingMessage{
			EventID:    e.ID,
			TTLSeconds: ttl,
			Expiration: expiration,
			CreatedAt:  createdAt,
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO moss_api.dismsg_messages (event_id, ttl_seconds, expiration, created_at)
            VALUES ($1, $2, $3, $4)
            ON CONFLICT (event_id) DO UPDATE SET
                ttl_seconds = EXCLUDED.ttl_seconds,
                expiration = EXCLUDED.expiration,
                created_at = EXCLUDED.created_at`,
			msg.EventID, msg.TTLSeconds, msg.Expiration, msg.CreatedAt); err != nil {
			s.Log.Errorf("Failed to store disappearing message %s: %v", e.ID, err)
		}
		s.Log.Infof("Successfully saved disappearing message %s (TTL: %d, Expires: %s)",
			e.ID, ttl, expiration.Format(time.RFC3339))
	}		
	return nil
}

// StartDisappearingMessageCleanup starts a goroutine that periodically cleans up expired messages
func StartDisappearingMessageCleanup(ctx context.Context, store DisappearingMessageStore, interval time.Duration) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			if err := store.DeleteExpiredMessages(ctx); err != nil {
				// Log error but continue - you might want to add proper logging here
			}
		}
	}
}
